version: "3.8"
services:
  audiobookshelf:
    container_name: Audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf
    volumes:
      - /home/config/audiobookshelf:/config
      - /home/config/audiobookshelf/metadata:/metadata
      - /mnt/nas1media/Audiobooks:/audiobooks
    ports:
      - 10000:80
    environment:
      AUDIOBOOKSHELF_UID: 99
      AUDIOBOOKSHELF_GID: 100
    restart: unless-stopped