version: "3.8"
services:
  komga:
    container_name: Komga
    image: gotson/komga
    volumes:
      - /home/config/komga:/config
      - /mnt/nas1media/Comics:/books
    ports:
      - 10001:25600
    environment:
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
    restart: unless-stopped