version: "3.8"
services:
  prowlarr:
    container_name: Prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    volumes:
      - /home/config/prowlarr:/config
    ports:
      - 10005:9696
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    restart: unless-stopped
