version: "3.8"
services:
  radarr:
    container_name: Radarr
    image: lscr.io/linuxserver/radarr
    volumes:
      - /home/config/radarr:/config
      - /mnt/nas1media/Movies:/movies
      - /mnt/nas1media/Downloads:/downloads
    ports:
      - 10006:7878
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    restart: unless-stopped