version: "3.8"
services:
  sabnzbd:
    container_name: SABnzbd
    image: lscr.io/linuxserver/sabnzbd
    volumes:
      - /home/config/sabnzbd:/config
      - /mnt/nas1media/Downloads:/downloads
      - /mnt/nas1media/Downloads/Incomplete:/incomplete-downloads
    ports:
      - 10008:8080
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    restart: unless-stopped
