version: "3.8"
services:
  sonarr:
    container_name: Sonarr
    image: lscr.io/linuxserver/sonarr
    volumes:
      - /home/config/sonarr:/config
      - /mnt/nas1media/TV Shows:/tv
      - /mnt/nas1media/Downloads:/downloads
    ports:
      - 10009:8989
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    restart: unless-stopped
