version: "3.8"
services:
  tautulli:
    container_name: Tautulli
    image: lscr.io/linuxserver/tautulli
    volumes:
      - /home/config/tautulli:/config
    ports:
      - 10010:8181
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    restart: unless-stopped
