version: "3.8"
services:
  youtubedl:
    container_name: YoutubeDL
    image: alexta69/metube
    volumes:
      - /mnt/nas1media/Downloads/Youtube:/downloads
    ports:
      - 10010:8081
    restart: unless-stopped