version: '3.8'
networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
services:
  wings:
    container_name: pterodactyl-node
    image: ghcr.io/pterodactyl/wings
    networks:
      - wings0
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pterodactyl/:/etc/pterodactyl/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
    ports:
      - "8080:8080"
      - "2022:2022"
      - "443:443"
    environment:
      TZ: "Europe/London"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    restart: unless-stopped
