version: '2'
networks:
  default:
    ipam:
      config:
        - subnet: 172.30.0.0/16
services:
  pterodactyl-database:
    container_name: Pterodactyl-DB
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: pterodb
      MYSQL_USER: ptero
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped
  pterodactyl-cache:
    container_name: Pterodactyl-REDIS
    image: redis:alpine
    restart: unless-stopped
  pterodactyl-panel:
    container_name: Pterodactyl-Panel
    image: ghcr.io/pterodactyl/panel
    links:
      - pterodactyl-database
      - pterodactyl-cache
    volumes:
      - "/srv/pterodactyl/var/:/app/var/"
      - "/srv/pterodactyl/nginx/:/etc/nginx/conf.d/"
      - "/srv/pterodactyl/certs/:/etc/letsencrypt/"
      - "/srv/pterodactyl/logs/:/var/log/"
    ports:
      - "80:80"
      - "443:443"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_THEME: pterodactyl
      APP_CLEAR_TASKLOG: 720
      APP_DELETE_MINUTES: 10
      APP_ENVIRONMENT_ONLY: false
      QUEUE_HIGH: high
      QUEUE_STANDARD: standard
      QUEUE_LOW: low
      TRUSTED_PROXIES: '*'
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: pterodactyl-cache
      REDIS_PORT: 6379
      APP_URL: "${APP_URL}"
      APP_TIMEZONE: Europe/London
      DB_HOST: pterodactyl-database
      DB_PORT: 3306
      DB_DATABASE: pterodb
      DB_USERNAME: ptero
      DB_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped
