version: "3.8"
services:
  audiobookshelf:
    container_name: Audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf
    restart: unless-stopped
    environment:
      AUDIOBOOKSHELF_UID: 99
      AUDIOBOOKSHELF_GID: 100
    volumes:
      - /glusterfs/bricks/gv0/containers/audiobookshelf:/config
      - /glusterfs/bricks/gv0/containers/audiobookshelf/metadata:/metadata
      - /mnt/nas1media/Audiobooks:/audiobooks
    ports:
      - 280:80
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.audiobookshelf.entrypoints: https
      traefik.http.routers.audiobookshelf.tls: true
      traefik.http.routers.audiobookshelf.rule: Host(`audiobooks.hyvecloud.dev`)
      traefik.http.routers.audiobookshelf.service: audiobookshelf-audiobookshelf@docker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true