version: "3.8"
services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf
    restart: unless-stopped
    environment:
      AUDIOBOOKSHELF_UID: 99
      AUDIOBOOKSHELF_GID: 100
    volumes:
      - /mnt/gluster/containers/audiobookshelf:/config
      - /mnt/gluster/containers/audiobookshelf/metadata:/metadata
      - /mnt/nas-01/Audiobooks:/audiobooks
    ports:
      - 80:80
