version: "3.8"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: https://docs.hyvecloud.dev
      DB_HOST: bookstack_db
      DB_PORT: 3306
      DB_USER: bookstack
      DB_PASS: "${DB_PASS}"
      DB_DATABASE: bookstackapp
    volumes:
      - /mnt/gluster/containers/bookstack/data:/config
    ports:
      - 8001:80
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      TZ: Europe/London
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - /mnt/gluster/containers/bookstack/db_data:/config