version: "3.8"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: Bookstack
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: https://docs.hyvecloud.dev
      DB_HOST: bookstack_db
      DB_PORT: 3306
      DB_USER: bookstack
      DB_PASS: "${DB_PASS}"
      DB_DATABASE: bookstackapp
    volumes:
      - /mnt/gluster/containers/bookstack/data:/config
    ports:
      - 9026:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.entrypoints=https"
      - "traefik.http.routers.bookstack.tls=true"
      - "traefik.http.routers.bookstack.rule=Host(`docs.hyvecloud.dev`)"
      - "traefik.http.routers.bookstack.service=bookstack-bookstack@docker"
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
    env_file:
      - .env
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: BookstackDB
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      TZ: Europe/London
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - /mnt/gluster/containers/bookstack/db_data:/config
    restart: unless-stopped
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
    env_file:
      - .env
networks:
  proxy:
    external: true