version: '3.8'
services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: Cloudflare-Tunnel
    hostname: cloudflare-tunnel
    restart: unless-stopped
    network_mode: "host"
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/gluster/containers/cloudflare-tunnel/config/hosts:/etc/hosts
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"