version: "3.8"
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      DELUGE_LOGLEVEL: error
      DOCKER_MODS: 'ghcr.io/gilbn/theme.park:deluge'
      TP_THEME: 'nord'
    volumes:
      - /mnt/gluster/containers/deluge:/config
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp