version: "3.8"
services:
  deluge:
    container_name: Deluge
    image: lscr.io/linuxserver/deluge:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error
    volumes:
      - /mnt/gluster/containers/deluge:/config
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.entrypoints=https"
      - "traefik.http.routers.deluge.tls=true"
      - "traefik.http.routers.deluge.rule=Host(`torrents.hyvecloud.dev`)"
      - "traefik.http.routers.deluge.service=deluge-deluge@docker"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true