version: "3.8"
services:
  dozzle:
    container_name: Docker-Socket-Proxy
    image: tecnativa/docker-socket-proxy
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
