version: "3.8"
services:
  dozzle:
    container_name: Dozzle
    image: amir20/dozzle:latest
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    environment:
      DOZZLE_REMOTE_HOST: "tcp://192.168.0.160:2375|PROXY,tcp://192.168.0.161:2375|MEDIA,tcp://192.168.0.162:2375|SERVICES"
      DOZZLE_HOSTNAME: "MANAGEMENT"
