version: "3.8"
services:
  excalidraw:
    container_name: Excalidraw
    image: kiliandeca/excalidraw
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      BACKEND_V2_GET_URL: http://localhost:8383/api/v2/scenes/
      BACKEND_V2_POST_URL: http://localhost:8383/api/v2/scenes/
      LIBRARY_URL: https://libraries.excalidraw.com
      LIBRARY_BACKEND: https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries
      SOCKET_SERVER_URL: http://localhost:8003/
      STORAGE_BACKEND: "http"
      HTTP_STORAGE_BACKEND_URL: "http://localhost:8383/api/v2"
    ports:
      - 8002:80
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.entrypoints=https"
      - "traefik.http.routers.excalidraw.tls=true"
      - "traefik.http.routers.excalidraw.rule=Host(`whiteboard.hyvecloud.dev`)"
      - "traefik.http.routers.excalidraw.service=excalidraw-excalidraw@docker"
    depends_on:
      - excalidraw-storage-backend
      - excalidraw-room
      - excalidraw-redis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
  excalidraw-storage-backend:
    container_name: Excalidraw-Storage
    image: kiliandeca/excalidraw-storage-backend
    restart: unless-stopped
    environment:
      STORAGE_URI: redis://redis:6379
    ports:
      - 8383:8080
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
  excalidraw-room:
    container_name: Excalidraw-Room
    image: excalidraw/excalidraw-room
    restart: unless-stopped
    ports:
      - "8003:80"
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
  excalidraw-redis:
    container_name: Excalidraw-REDIS
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true