version: "3.8"
services:
  excalidraw:
    image: kiliandeca/excalidraw
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      BACKEND_V2_GET_URL: http://localhost:8383/api/v2/scenes/
      BACKEND_V2_POST_URL: http://localhost:8383/api/v2/scenes/
      LIBRARY_URL: https://libraries.excalidraw.com
      LIBRARY_BACKEND: https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries
      SOCKET_SERVER_URL: http://localhost:8003/
      STORAGE_BACKEND: "http"
      HTTP_STORAGE_BACKEND_URL: "http://localhost:8383/api/v2"
    ports:
      - 8002:80
    depends_on:
      - excalidraw_storage_backend
      - excalidraw_room
      - excalidraw_redis
  excalidraw_storage-backend:
    image: kiliandeca/excalidraw-storage-backend
    restart: unless-stopped
    environment:
      STORAGE_URI: redis://redis:6379
    ports:
      - 8383:8080
  excalidraw_room:
    image: excalidraw/excalidraw-room
    restart: unless-stopped
    ports:
      - "8003:80"
  excalidraw_redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"