version: "3.8"
services:
  filebrowser:
    container_name: Filebrowser
    image: hurlenko/filebrowser
    volumes:
      - /mnt/gluster/containers/file-browser:/config
      - /mnt/gluster/containers:/data
    ports:
      - 9001:8080
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-browser.entrypoints=https"
      - "traefik.http.routers.file-browser.tls=true"
      - "traefik.http.routers.file-browser.rule=Host(`file-browser.hyvecloud.dev`)"
      - "traefik.http.routers.file-browser.service=filebrowser-filebrowser@docker"
networks:
  proxy:
    external: true