version: "3.8"
services:
  filebrowser:
    image: hurlenko/filebrowser
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - /mnt/gluster/containers/file-browser:/config
      - /mnt/gluster/containers:/data
    ports:
      - 8181:8080