version: '3.8'
services:
  guacamole:
    image: jasonbean/guacamole
    restart: unless-stopped
    environment:
      OPT_MYSQL: Y
    volumes:
    - /mnt/gluster/containers/guacamole:/config
    ports:
    - 8282:8080
