version: '3.8'
services:
  guacamole:
    container_name: Guacamole
    image: abesnier/guacamole
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      EXTENSIONS: 'auth-sso-openid'
    volumes:
      - /mnt/gluster/containers/guacamole:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
    - 8181:8080
