version: '3.8'
services:
  guacamole:
    image: flcontainers/guacamole
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'UTC'
      EXTENSIONS: 'auth-totp,auth-ldap'
    volumes:
      - /mnt/gluster/containers/guacamole:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
    - 8282:8080
