version: '3.8'
services:
  homepage:
    container_name: Homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - /mnt/gluster/containers/homepage:/app/config
      - /mnt/gluster/containers/homepage/images:/app/public/images
    ports:
      - 3000:3000
