version: "3.8"
services:
  home-assistant:
    container_name: Home-Assistant
    image: lscr.io/linuxserver/homeassistant
    network_mode: host
    volumes:
      - /home/config/home-assistant:/config
    ports:
      - 13001:8123
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    restart: unless-stopped