version: '3.8'
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: Homepage
    ports:
      - 9020:3000
    volumes:
      - /mnt/gluster/containers/homepage:/app/config
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=https"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.rule=Host(`dashboard.hyvecloud.dev`)"
      - "traefik.http.routers.homepage.service=homepage-homepage@docker"
networks:
  proxy:
    external: true