version: "3.8"
services:
  home-assistant:
    image: lscr.io/linuxserver/homeassistant
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - /mnt/gluster/containers/home-assistant:/config
    network: host