version: '3.8'
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    volumes:
      - /mnt/gluster/containers/homepage:/app/config
    ports:
      - 3001:3000