version: "3.8"
services:
  kavita:
    image: kizaing/kavita:latest
    restart: unless-stopped
    volumes:
      - /mnt/gluster/containers/kavita:/kavita/config
      - /mnt/nas-01/Comics:/books
    ports:
      - 5000:5000