version: "3.8"
services:
  kavita:
    container_name: Kavita
    image: kizaing/kavita:latest
    restart: unless-stopped
    volumes:
      - /mnt/gluster/containers/kavita:/kavita/config
      - /mnt/nas-01/Comics:/books
    ports:
      - 5000:5000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.entrypoints=https"
      - "traefik.http.routers.kavita.tls=true"
      - "traefik.http.routers.kavita.rule=Host(`comics.hyvecloud.dev`)"
      - "traefik.http.routers.kavita.service=kavita-kavita@docker"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true