version: "3.8"
services:
  kavita:
    container_name: Komga
    image: gotson/komga:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      JAVA_TOOL_OPTIONS: '-Xmx4g'
    volumes:
      - /mnt/gluster/containers/komga:/config
      - /mnt/nas-01/Comics:/data
    ports:
      - 25600:25600