version: "3.8"
services:
###
  tautulli:
    container_name: Tautulli
    image: lscr.io/linuxserver/tautulli:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:tautulli
      - TP_THEME=nord
    volumes:
      - /mnt/gluster/containers/tautulli:/config
    ports:
      - 8181:8181
    networks:
      - media-management
###
  overseerr:
    container_name: Overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:overseerr
      - TP_THEME=nord
    volumes:
      - /mnt/gluster/containers/overseerr:/config
    ports:
      - 5055:5055
    networks:
      - media-management
###
  plex-meta-manager:
    container_name: Plex-Meta-Manager
    image: lscr.io/linuxserver/plex-meta-manager:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PMM_CONFIG=/config/config.yml
      - PMM_TIME=00:00
    volumes:
      - /mnt/gluster/containers/plex-meta-manager:/config
###
  youtubedl:
    container_name: YoutubeDL
    image: ghcr.io/alexta69/metube:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    volumes:
      - /mnt/nas-01/Downloads/Youtube:/downloads
    ports:
      - 8081:8081
    networks:
      - media-management
###
networks:
  media-management:
    driver: bridge
