version: '3.8'
services:
  monitoror:
    container_name: Monitoror
    image: monitoror/monitoror
    restart: unless-stopped
    environment:
      MO_CONFIG: /configs/config.json
    volumes:
      - /mnt/gluster/containers/monitoror:/configs
    ports:
      - 8484:8080
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoror.entrypoints=https"
      - "traefik.http.routers.monitoror.tls=true"
      - "traefik.http.routers.monitoror.rule=Host(`monitoror.hyvecloud.dev`)"
      - "traefik.http.routers.monitoror.service=monitoror-monitoror@docker"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true
