version: "3.8"
services:
###
  uptime-kuma:
    container_name: Uptime-Kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    volumes:
      - /mnt/gluster/containers/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    networks:
      - monitoring-services
###
  speedtest-tracker:
    container_name: Speedtest-Tracker
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    restart: unless-stopped
    ports:
      - 180:80
      - 1443:443
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: "mysql"
      DB_HOST: "speedtest-db"
      DB_PORT: "3306"
      DB_DATABASE: "speedtest_tracker"
      DB_USERNAME: "speedy"
      DB_PASSWORD: "${SPEEDTEST_TRACKER_DB_PASSWORD}"
    volumes:
      - /mnt/gluster/containers/speedtest-tracker:/config
    networks:
      - monitoring-services
      - speedtest-tracker
    depends_on:
      - speedtest-db
  speedtest-db:
    container_name: Speedtest-Tracker-DB
    image: mariadb:10
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: "speedtest_tracker"
      MARIADB_USER: "speedy"
      MARIADB_PASSWORD: "${SPEEDTEST_TRACKER_DB_PASSWORD}"
      MARIADB_RANDOM_ROOT_PASSWORD: true
    volumes:
      - /mnt/gluster/containers/speedtest-tracker/db:/var/lib/mysql
    networks:
      - monitoring-services
      - speedtest-tracker
###
  dozzle:
    container_name: Dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_REMOTE_HOST=tcp://192.168.10.161:2375|VM-DOCKER-PROXY,tcp://192.168.10.163:2375|VM-DOCKER-MEDIA,tcp://192.168.10.164:2375|VM-DOCKER-SERVICES
      - DOZZLE_HOSTNAME=VM-DOCKER-MANAGEMENT
    ports:
      - 9999:8080
    networks:
      - management-services
###
  filebrowser:
    container_name: Filebrowser
    image: hurlenko/filebrowser:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - FB_NOAUTH=noauth
    volumes:
      - /mnt/gluster/containers/file-browser:/config
      - /mnt/gluster/containers/file-browser/branding:/branding
      - /mnt/gluster/containers:/data
    ports:
      - 9898:8080
    networks:
      - management-services
###
#  guacamole:
#    container_name: Guacamole
#    image: abesnier/guacamole:latest
#    restart: unless-stopped
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - EXTENSIONS=auth-sso-openid
#    volumes:
#      - /mnt/gluster/containers/guacamole:/config
#      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 9797:8080
#    networks:
#      - management-services
###
  upsnap:
    container_name: Upsnap
    image: ghcr.io/seriousm4x/upsnap:latest
    restart: unless-stopped
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5001"
    healthcheck:
      test: curl -fs "http://localhost:5001/api/health" || exit 1
      interval: 10s
    environment:
      - TZ=Europe/London
      - UPSNAP_WEBSITE_TITLE=Hyvecloud Host Management
    volumes:
      - /mnt/gluster/containers/upsnap:/app/pb_data
    network_mode: host
###
  homepage:
    container_name: Homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - /mnt/gluster/containers/homepage:/app/config
      - /mnt/gluster/containers/homepage/images:/app/public/images
      - /mnt/gluster/containers/homepage/icons:/app/public/icons
    ports:
      - 3000:3000
    networks:
      - management-services
###
networks:
  monitoring-services:
    driver: bridge
  management-services:
    driver: bridge
  speedtest-tracker:
