version: '3.8'
services:
  monitoror:
    container_name: Monitoror
    image: monitoror/monitoror
    restart: unless-stopped
    environment:
      MO_CONFIG: /configs/config.json
    volumes:
      - /mnt/gluster/containers/monitoror:/configs
    ports:
      - 8484:8080