version: "3.8"
services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    command: "mosquitto -c /mosquitto-no-auth.conf"
    volumes:
      - /mnt/gluster/containers/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9002:9001
    
