version: "3.8"
services:
  mqtt:
    container_name: MQTT
    image: eclipse-mosquitto
    command: "mosquitto -c /mosquitto-no-auth.conf"
    volumes:
      - /home/config/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 13002:9001
    restart: unless-stopped