version: "3.8"
services:
  mylar:
    container_name: Mylar
    image: lscr.io/linuxserver/mylar3
    volumes:
      - /home/config/mylar:/config
      - /mnt/nas1media/Comics:/comics
      - /mnt/nas1media/Downloads:/downloads
    ports:
      - 8090:8090
    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
