version: "3.8"
services:
  mylar:
    image: lscr.io/linuxserver/mylar3
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      DOCKER_MODS: 'ghcr.io/gilbn/theme.park:mylar3'
      TP_THEME: 'nord'
    volumes:
      - /mnt/gluster/containers/mylar:/config
      - /mnt/nas-01/Comics:/comics
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 8090:8090
