version: "3.8"
services:
  mylar:
    container_name: Mylar
    image: lscr.io/linuxserver/mylar3
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/gluster/containers/mylar:/config
      - /mnt/nas-01/Comics:/comics
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 8090:8090
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mylar.entrypoints=https"
      - "traefik.http.routers.mylar.tls=true"
      - "traefik.http.routers.mylar.rule=Host(`mylar.hyvecloud.dev`)"
      - "traefik.http.routers.mylar.service=mylar-mylar@docker"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true
