version: "3.8"
services:
  mylar:
    image: lscr.io/linuxserver/mylar3
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/gluster/containers/mylar:/config
      - /mnt/nas-01/Comics:/comics
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 8090:8090
