version: '3.8'
services:
  nginx-proxy-manager:
    container_name: NGINX-Proxy-Manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    volumes:
      - /mnt/gluster/containers/nginx-proxy-manager:/data
      - /mnt/gluster/containers/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    