version: '3.8'
services:
  omada-controller:
    image: mbentley/omada-controller:5.9
    restart: unless-stopped
    environment:
      MANAGE_HTTP_PORT: 480
      MANAGE_HTTPS_PORT: 4443
      PORTAL_HTTP_PORT: 580
      PORTAL_HTTPS_PORT: 5443
      PORT_APP_DISCOVERY: 27001
      PORT_ADOPT_V1: 29812
      PORT_UPGRADE_V1: 29813
      PORT_MANAGER_V1: 29811
      PORT_MANAGER_V2: 29814
      PORT_DISCOVERY: 29810
      SHOW_SERVER_LOGS: true
      TZ: Europe/London
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    volumes:
      - /mnt/gluster/containers/omada/data:/opt/tplink/EAPController/data
      - /mnt/gluster/containers/omada/logs:/opt/tplink/EAPController/logs
    network: host
  
    