version: '3'
services:
  overseerr:
    image: sctx/overseerr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
    volumes:
      - /mnt/gluster/containers/overseerr:/app/config
    ports:
      - 5055:5055