version: '3'
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/gluster/containers/overseerr:/config
    ports:
      - 5055:5055
