version: "3.8"
services:
  paperless-ngx:
    container_name: Paperless-NGX
    image: paperlessngx/paperless-ngx
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      PAPERLESS_URL: https://paperless.hyvecloud.dev
      PAPERLESS_REDIS: redis://paperless-ngx-redis:6379
      PAPERLESS_DBHOST: paperless-ngx-db
      PAPERLESS_ADMIN_USER: abeckett
      PAPERLESS_ADMIN_MAIL: becketta@live.com
      PAPERLESS_ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      PAPERLESS_DBPASS: "${DB_PASS}"
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-ngx-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-ngx-tika:9998
    env_file:
      - .env
    volumes:
      - /mnt/gluster/containers/paperless-ngx/config:/config
      - /mnt/gluster/containers/paperless-ngx/data:/data
    ports:
      - '8004:8000'
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless-ngx.entrypoints=https"
      - "traefik.http.routers.paperless-ngx.tls=true"
      - "traefik.http.routers.paperless-ngx.rule=Host(`paperless.hyvecloud.dev`)"
      - "traefik.http.routers.paperless-ngx.service=paperless-ngx-paperless-ngx@docker"
    depends_on:
      - paperless-ngx-redis
      - paperless-ngx-db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
  paperless-ngx-redis:
    container_name: Paperless-NGX-REDIS
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
  paperless-ngx-db:
    container_name: Paperless-NGX-DB
    image: docker.io/library/postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: "${DB_PASS}"
    env_file:
      - .env
    volumes:
      - /mnt/gluster/containers/paperless-ngx/pgdata:/var/lib/postgresql/data
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
  paperless-ngx-gotenberg:
    container_name: Paperless-NGX-Gotenberg
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
  paperless-ngx-tika:
    container_name: Paperless-NGX-Tika
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true