version: "3.8"
services:
  paperless_ngx:
    image: paperlessngx/paperless-ngx:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      PAPERLESS_URL: https://paperless.hyvecloud.dev
      PAPERLESS_REDIS: redis://paperless_ngx_redis:6379
      PAPERLESS_DBHOST: paperless_ngx_db
      PAPERLESS_ADMIN_USER: abeckett
      PAPERLESS_ADMIN_MAIL: becketta@live.com
      PAPERLESS_ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      PAPERLESS_DBPASS: "${DB_PASS}"
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless_ngx_gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless_ngx_tika:9998
    volumes:
      - /mnt/gluster/containers/paperless-ngx/config:/config
      - /mnt/gluster/containers/paperless-ngx/data:/data
    ports:
      - '8004:8000'
    depends_on:
      - paperless_ngx_redis
      - paperless_ngx_db
      - paperless_ngx_gotenberg
      - paperless_ngx_tika
  paperless_ngx_redis:
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
  paperless_ngx_db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: "${DB_PASS}"
    volumes:
      - /mnt/gluster/containers/paperless-ngx/pgdata:/var/lib/postgresql/data
  paperless_ngx_gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  paperless_ngx_tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
