version: "3.8"
services:
  planka:
    image: ghcr.io/plankanban/planka:latest
    restart: unless-stopped
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    environment:
      BASE_URL: https://board.hyvecloud.dev
      TRUST_PROXY: 1
      DATABASE_URL: postgresql://postgres@planka_db/planka
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - /mnt/gluster/containers/planka/user-avatars:/app/public/user-avatars
      - /mnt/gluster/containers/planka/project-background-images:/app/public/project-background-images
      - /mnt/gluster/containers/planka/attachments:/app/private/attachments
    ports:
      - 1337:1337
    depends_on:
      - planka_db
  planka_db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: planka
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /mnt/gluster/containers/planka/db-data:/var/lib/postgresql/data