version: "3.8"
services:
  planka:
    container_name: Planka
    image: ghcr.io/plankanban/planka:latest
    restart: unless-stopped
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    environment:
      - BASE_URL=https://board.hyvecloud.dev
      - TRUST_PROXY=1
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=${SECRET_KEY}
      - OIDC_ISSUER=${OIDC_ISSUER}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_SCOPES=openid email profile
      - OIDC_ADMIN_ROLES=admin
      - OIDC_EMAIL_ATTRIBUTE=email
      - OIDC_NAME_ATTRIBUTE=name
      - OIDC_USERNAME_ATTRIBUTE=preferred_username
    volumes:
      - /mnt/gluster/containers/planka/user-avatars:/app/public/user-avatars
      - /mnt/gluster/containers/planka/project-background-images:/app/public/project-background-images
      - /mnt/gluster/containers/planka/attachments:/app/private/attachments
    ports:
      - 1337:1337
    depends_on:
      - postgres
  postgres:
    container_name: Planka-DB
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - planka-db-data:/var/lib/postgresql/data
volumes:
  planka-db-data: