version: "3.8"
services:
  planka:
    container_name: Planka
    image: ghcr.io/plankanban/planka:latest
    restart: unless-stopped
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    environment:
      BASE_URL: https://board.hyvecloud.dev
      TRUST_PROXY: 1
      DATABASE_URL: postgresql://postgres@postgres/planka
      SECRET_KEY: "${SECRET_KEY}"
    env_file:
      - .env
    volumes:
      - /glusterfs/bricks/gv0/containers/planka/user-avatars:/app/public/user-avatars
      - /glusterfs/bricks/gv0/containers/planka/project-background-images:/app/public/project-background-images
      - /glusterfs/bricks/gv0/containers/planka/attachments:/app/private/attachments
    ports:
      - 1337:1337
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.planka.entrypoints=https"
      - "traefik.http.routers.planka.tls=true"
      - "traefik.http.routers.planka.rule=Host(`board.hyvecloud.dev`)"
      - "traefik.http.routers.planka.service=planka-planka@docker"
    depends_on:
      - planka-db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
  planka-db:
    container_name: Planka-DB
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: planka
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /glusterfs/bricks/gv0/containers/planka/db-data:/var/lib/postgresql/data
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true