version: "3.8"
services:
  plex-meta-manager:
    image: meisnate12/plex-meta-manager
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    volumes:
      - /mnt/gluster/containers/plex-meta-manager:/config