version: '3.2'
services:
  agent:
    name: portainer_agent
    image: portainer/agent:2.18.4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001