version: "3.8"
services:
  prowlarr:
    container_name: Prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - /mnt/gluster/containers/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.hyvecloud.dev`)"
      - "traefik.http.routers.prowlarr.service=prowlarr-prowlarr@docker"   
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true
