version: "3.8"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      DOCKER_MODS: 'ghcr.io/gilbn/theme.park:prowlarr'
      TP_THEME: 'nord'
    volumes:
      - /mnt/gluster/containers/prowlarr:/config
    ports:
      - 9696:9696
