version: "3.8"
services:
  qbittorrent:
    container_name: qBittorrent
    image: ghcr.io/hotio/qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /mnt/gluster/containers/qbittorrent:/config
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 8112:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
