version: "3.8"
services:
  qbittorrent:
    container_name: qBittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      WEBUI_PORT: 8112
      DOCKER_MODS: 'ghcr.io/themepark-dev/theme.park:qbittorrent'
      TP_DOMAIN: 'theme-park.dev'
      TP_THEME: 'nord'
    volumes:
      - /mnt/gluster/containers/qbittorrent:/config
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
