version: "3.8"
services:
  radarr:
    container_name: Radarr
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - /mnt/gluster/containers/radarr:/config
      - /mnt/nas-01/Movies:/movies
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.hyvecloud.dev`)"
      - "traefik.http.routers.radarr.service=radarr-radarr@docker"   
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true
