version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - /mnt/gluster/containers/radarr:/config
      - /mnt/nas-01/Movies:/movies
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 7878:7878
