version: "3.8"
services:
  sabnzbd:
    container_name: SABnzbd
    image: lscr.io/linuxserver/sabnzbd
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      DOCKER_MODS: 'ghcr.io/themepark-dev/theme.park:sabnzbd'
      TP_THEME: 'nord'
    volumes:
      - /mnt/gluster/containers/sabnzbd:/config
      - /mnt/nas-01/Downloads:/downloads
      - /mnt/nas-01/Downloads/Incomplete:/incomplete-downloads
    ports:
      - 8787:8080
