version: "3.8"
services:
  sabnzbd:
    container_name: SABnzbd
    image: lscr.io/linuxserver/sabnzbd
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - /glusterfs/bricks/gv0/containers/sabnzbd:/config
      - /mnt/nas1media/Downloads:/downloads
      - /mnt/nas1media/Downloads/Incomplete:/incomplete-downloads
    ports:
      - 8585:8080
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.entrypoints=https"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.hyvecloud.dev`)"
      - "traefik.http.routers.sabnzbd.service=sabnzbd-sabnzbd@docker"   
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true