version: "3.8"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - /mnt/gluster/containers/sabnzbd:/config
      - /mnt/nas-01/Downloads:/downloads
      - /mnt/nas-01/Downloads/Incomplete:/incomplete-downloads
    ports:
      - 8585:8080