version: '3.8'
services:
  ansible-semaphore:
    image: ghcr.io/imagegenius/semaphore:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: abeckett
      SEMAPHORE_ADMIN_PASSWORD: "${PASSWORD}"
      SEMAPHORE_ADMIN_NAME: Adam Beckett
      SEMAPHORE_ADMIN_EMAIL: becketta@live.com
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: "${ENCRYPTION_KEY}"
    volumes:
      - /mnt/gluster/containers/semaphore:/config
    ports:
      - 3000:3000
