version: '3.8'
services:
  ansible-semaphore:
    container_name: Ansible-Semaphore
    image: ghcr.io/imagegenius/semaphore:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: abeckett
      SEMAPHORE_ADMIN_PASSWORD: "${PASSWORD}"
      SEMAPHORE_ADMIN_NAME: Adam Beckett
      SEMAPHORE_ADMIN_EMAIL: becketta@live.com
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: "${ENCRYPTION_KEY}"
    env_file:
      - .env
    volumes:
      - /mnt/gluster/containers/semaphore:/config
    ports:
      - 3000:3000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ansible-semaphore.entrypoints=https"
      - "traefik.http.routers.ansible-semaphore.tls=true"
      - "traefik.http.routers.ansible-semaphore.rule=Host(`ansible-2.hyvecloud.dev`)"
      - "traefik.http.routers.ansible-semaphore.service=ansible-semaphore-ansible-semaphore@docker"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true
