version: "3.8"
services:
  shepherd:
    image: mazzolino/shepherd
    build: .
    restart: unless-stopped
    environment:
      TZ: "Europe/London"
      SLEEP_TIME: "5m"
      VERBOSE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager
