version: "3.8"
services:
  sonarr:
    container_name: Sonarr
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      DOCKER_MODS: 'ghcr.io/gilbn/theme.park:sonarr'
      TP_THEME: 'nord'
    volumes:
      - /mnt/gluster/containers/sonarr:/config
      - /mnt/nas-01/TV Shows:/tv
      - /mnt/nas-01/Downloads:/downloads
    ports:
      - 8989:8989
