version: '3.8'
services:
  speedtest-tracker:
    container_name: Speedtest-Tracker
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: speedtest_tracker_db
      DB_PORT: 5432
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: speedtest
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - '/mnt/gluster/containers/speedtest-tracker:/config'
    ports:
      - 180:80
      - 1443:443
    depends_on:
      - speedtest_tracker_db
  speedtest_tracker_db:
    container_name: Speedtest-Tracker-DB
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: speedtest_tracker
      POSTGRES_USER: speedtest
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - /mnt/gluster/containers/speedtest-tracker/db:/var/lib/postgresql/data