version: '3.8'
services:
  speedtest-tracker:
    container_name: Speedtest-Tracker
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: 192.168.0.162
      DB_PORT: 5432
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: postgres
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - '/mnt/gluster/containers/speedtest-tracker:/config'
    ports:
      - 180:80
      - 1443:443
    depends_on:
      - speedtest-tracker-db
  speedtest-tracker-db:
    container_name: Speedtest-Tracker-DB
    image: postgres:15
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      POSTGRES_DB: speedtest_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - /mnt/gluster/containers/speedtest-tracker/db:/var/lib/postgresql/data