version: '3.8'
services:
  speedtest-tracker:
    container_name: Speedtest-Tracker
    ports:
      - 180:80
      - 1443:443
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: speedtest-tracker-db
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: speedtest
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - '/home/config/speedtest-tracker:/config'
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    restart: unless-stopped
    depends_on:
      - speedtest-tracker-db
    env_file:
      - .env
  speedtest-tracker-db:
    container_name: Speedtest-Tracker-DB
    image: mariadb:10
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: speedtest_tracker
      MARIADB_USER: speedtest
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_RANDOM_ROOT_PASSWORD: true
    volumes:
      - speedtest-db:/var/lib/mysql
    env_file:
      - .env
volumes:
  speedtest-db: