version: '3'
services:
  traefik:
    container_name: Traefik
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /glusterfs/bricks/gv0/containers/traefik/:/etc/traefik
      - /glusterfs/bricks/gv0/containers/traefik/traefik.yml:/traefik.yml
      - /glusterfs/bricks/gv0/containers/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.hyvecloud.dev`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth@file"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true