version: '3.8'
services:
  truecommand:
    image: ixsystems/truecommand
    restart: unless-stopped
    environment:
      TZ: Europe/London
    volumes:
      - /mnt/gluster/containers/truecommand:/data
    ports:
      - 380:80