version: "3.8"
services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:4
    restart: unless-stopped
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5001"
    healthcheck:
      test: curl -fs "http://localhost:5001/api/health" || exit 1
      interval: 10s
    environment:
      TZ: Europe/London
      UPSNAP_SCAN_RANGE: 192.168.0.1/24
      UPSNAP_WEBSITE_TITLE: 'HyveCloud WoL'
    volumes:
      - /mnt/gluster/containers/upsnap:/app/pb_data
    network: host
