version: "3.8"
services:
  upsnap:
    container_name: UpSnap
    image: ghcr.io/seriousm4x/upsnap:4
    restart: unless-stopped
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5001"
    healthcheck:
      test: curl -fs "http://localhost:5001/api/health" || exit 1
      interval: 10s
    environment:
      TZ: Europe/London
      UPSNAP_SCAN_RANGE: 192.168.0.1/24
      UPSNAP_WEBSITE_TITLE: 'HyveCloud WoL'
    volumes:
      - /glusterfs/bricks/gv0/containers/upsnap:/app/pb_data
    ports:
      - 5001:5001
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.upsnap.entrypoints=https"
      - "traefik.http.routers.upsnap.tls=true"
      - "traefik.http.routers.upsnap.rule=Host(`upsnap.hyvecloud.dev`)"
      - "traefik.http.routers.upsnap.service=upsnap-upsnap@docker"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true