version: '3.8'
services:
  uptime-kuma:
    container_name: Uptime-Kuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    volumes:
        - /mnt/gluster/containers/uptime-kuma:/app/data
    ports:
        - 3002:3001
