version: '3.8'
services:
  uptime-kuma:
    container_name: Uptime-Kuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    volumes:
        - /mnt/gluster/containers/uptime-kuma:/app/data
    ports:
        - 3002:3001   
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=https"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.hyvecloud.dev`)"
      - "traefik.http.routers.uptime-kuma.service=uptime-kuma-uptime-kuma@docker"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true
