version: "3"
services: 
  valheim-server: 
    image: ghcr.io/lloesche/valheim-server
    container_name: Valheim-Server
    cap_add:
      - sys_nice
    volumes: 
      - /mnt/gluster/containers/valheim-server/config:/config
      - /mnt/gluster/containers/valheim-server/data:/opt/valheim
    ports: 
      - 2456:2456/udp
      - 2457:2457/udp
      - 9010:9010
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVER_NAME="TheRedshift - Valheim"
      - SERVER_PORT=2456
      - SERVER_PASS=${VALHEIM_SERVER_PASSWORD}
      - WORLD_NAME=TheShadowLand
      - SERVER_PUBLIC=true
      - BACKUPS=true
      - BACKUPS_DIRECTORY=/config/backups
      - SUPERVISOR_HTTP=true
      - SUPERVISOR_HTTP_PORT=9010
      - SUPERVISOR_HTTP_USER=${VALHEIM_ADMIN_USER}
      - SUPERVISOR_HTTP_PASS=${VALHEIM_ADMIN_PASSWORD}
    restart: always
    stop_grace_period: 2m
