version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: Vaultwarden
    restart: unless-stopped
    ports:
     - 9445:80 #map any custom port to use (replace 8445 not 80)
    volumes:
     - ./bitwarden:/data:rw
    environment:
     - DOMAIN=${DOMAIN}
     - ADMIN_TOKEN=${ADMIN_TOKEN}
     - LOGIN_RATELIMIT_MAX_BURST=10
     - LOGIN_RATELIMIT_SECONDS=60
     - ADMIN_RATELIMIT_MAX_BURST=10
     - ADMIN_RATELIMIT_SECONDS=60
     - WEBSOCKET_ENABLED=true
     - SIGNUPS_ALLOWED=true
     - SENDS_ALLOWED=false
     - EMERGENCY_ACCESS_ALLOWED=true
     - WEB_VAULT_ENABLED=true
     - SMTP_HOST=${SMTP_HOST}
     - SMTP_FROM=${SMTP_FROM}
     - SMTP_FROM_NAME=Vaultwarden
     - SMTP_SECURITY=${SMTP_SECURITY}
     - SMTP_PORT=${SMTP_PORT}
     - SMTP_USERNAME=${SMTP_USERNAME}
     - SMTP_PASSWORD=${SMTP_PASSWORD}