version: "3.8"
services: 
  vscode-server:
    container_name: VSCode-Server
    image: lscr.io/linuxserver/code-server
    volumes:
      - /mnt/gluster/containers/vscode-server:/config
      - /mnt/gluster/containers:/containers
    ports:
      - 8443:8443
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      DEFAULT_WORKSPACE: /containers
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vscode-server.entrypoints=https"
      - "traefik.http.routers.vscode-server.tls=true"
      - "traefik.http.routers.vscode-server.rule=Host(`file-browser.hyvecloud.dev`)"
      - "traefik.http.routers.vscode-server.service=vscode-server-vscode-server@docker"
networks:
  proxy:
    external: true
