version: "3.8"
services: 
  vscode-server:
    image: lscr.io/linuxserver/code-server
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      DEFAULT_WORKSPACE: /containers
    volumes:
      - /mnt/gluster/containers/vscode-server:/config
      - /mnt/gluster/containers:/containers
    ports:
      - 8443:8443
