version: "3.8"
services:
  youtubedl:
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    environment:
      TZ: Europe/London
    volumes:
      - /mnt/nas-01/Downloads/Youtube:/downloads
    ports:
      - 8081:8081
