version: "3.8"
services:
  youtubedl:
    container_name: YoutubeDL
    image: alexta69/metube
    restart: unless-stopped
    volumes:
      - /mnt/nas1media/Downloads/Youtube:/downloads
    ports:
      - 8081:8081
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.youtubedl.entrypoints=https"
      - "traefik.http.routers.youtubedl.tls=true"
      - "traefik.http.routers.youtubedl.rule=Host(`youtubedl.hyvecloud.dev`)"
      - "traefik.http.routers.youtubedl.service=youtubedl-youtubedl@docker"   
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
networks:
  proxy:
    external: true
