version: "3.8"
services:
  youtubedl:
    image: alexta69/metube
    restart: unless-stopped
    environment:
      UID: 99
      GID: 100
      TZ: Europe/London
      DARK_MODE: true
    volumes:
      - /mnt/nas-01/Downloads/Youtube:/downloads
    ports:
      - 8081:8081
