version: "3.8"
services:
  zigbee2mqtt:
    container_name: Zigbee2MQTT
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    environment:
      TZ: Europe/London
    volumes:
      - /mnt/gluster/containers/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host