version: "3.8"
services:
  zigbee2mqtt:
    container_name: Zigbee2MQTT
    image: koenkk/zigbee2mqtt
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /home/config/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 13003:8080
    environment:
      TZ: Europe/London
    restart: unless-stopped