version: "3.8"
services:
  dozzle:
    container_name: Dozzle
    image: amir20/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9003:8080
    restart: unless-stopped