version: "3.8"
services:
  filebrowser:
    container_name: Filebrowser
    image: hurlenko/filebrowser
    volumes:
      - /home/config/file-browser:/config
      - /home/config:/data
    ports:
    - 9004:8080
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    restart: unless-stopped