version: '3.8'
services:
  guacamole:
    container_name: Guacamole
    image: jasonbean/guacamole
    volumes:
    - /mnt/gluster/containers/guacamole:/config
    ports:
    - 9003:8080
    environment:
      OPT_MYSQL: Y
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.entrypoints=https"
      - "traefik.http.routers.guacamole.tls=true"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.hyvecloud.dev`)"
      - "traefik.http.routers.guacamole.service=guacamole-guacamole@docker"
networks:
  proxy:
    external: true
