version: '3.8'
services:
  guacamole:
    container_name: Guacamole
    image: jasonbean/guacamole
    volumes:
    - /mnt/gluster/containers/guacamole:/config
    ports:
    - 10001:8080
    environment:
      OPT_MYSQL: Y
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
