version: '3.8'
services:
  ansible-semaphore:
    image: ghcr.io/imagegenius/semaphore:latest
    container_name: Ansible-Semaphore
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: "${ADMIN}"
      SEMAPHORE_ADMIN_PASSWORD: "${PASSWORD}"
      SEMAPHORE_ADMIN_NAME: "${NAME}"
      SEMAPHORE_ADMIN_EMAIL: "${EMAIL}"
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: "${ENCRYPTION_KEY}"
    volumes:
      - /home/config/semaphore:/config
    ports:
      - 9004:3000
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
