version: '3.8'
services:
  truecommand:
    container_name: TrueCommand
    image: ixsystems/truecommand
    volumes:
      - /mnt/gluster/containers/truecommand:/data
    ports:
      - 9005:80
    environment:
      TZ: Europe/London
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vscode-server.entrypoints=https"
      - "traefik.http.routers.vscode-server.tls=true"
      - "traefik.http.routers.vscode-server.rule=Host(`truecommand.hyvecloud.dev`)"
      - "traefik.http.routers.vscode-server.service=truecommand-truecommand@docker"
networks:
  proxy:
    external: true
