version: "3.8"
services:
  librenms-db:
    container_name: LibreNMS-DB
    image: mariadb:10.5
    command:
      - mysqld
      - --innodb-file-per-table=1
      - --lower-case-table-names=0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/config/librenms-db/:/var/lib/mysql
    environment:
      TZ: Europe/London
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: librenms
      MYSQL_USER: librenms
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped
  librenms-memcached:
    container_name: LibreNMS-Memcached
    image: memcached:alpine
    environment:
      TZ: Europe/London
    restart: unless-stopped
  librenms-redis:
    container_name: LibreNMS-REDIS
    image: redis:5.0-alpine
    environment:
      TZ: Europe/London
    restart: unless-stopped
  librenms:
    container_name: LibreNMS
    image: librenms/librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms-db
      - librenms-memcached
    volumes:
      - /home/config/librenms:/data
    ports:
      - 8001:8000
    environment:
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
      DB_HOST: librenms-db
      DB_NAME: librenms
      DB_USER: librenms
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_TIMEOUT: 60
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      MEMORY_LIMIT: 256M
      UPLOAD_MAX_SIZE: 16M
      OPCACHE_MEM_SIZE: 128
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      LOG_IP_VAR: remote_addr
      LIBRENMS_SNMP_COMMUNITY: "${SNMP_COMMUNITY}"
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
    restart: unless-stopped
  librenms-dispatcher:
    container_name: LibreNMS-Dispatcher
    image: librenms/librenms
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - librenms-redis
    volumes:
      - /home/config/librenms:/data
    environment:
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
      DB_HOST: db
      DB_NAME: librenms
      DB_USER: librenms
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_TIMEOUT: 60
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      MEMORY_LIMIT: 256M
      UPLOAD_MAX_SIZE: 16M
      OPCACHE_MEM_SIZE: 128
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      LOG_IP_VAR: remote_addr
      LIBRENMS_SNMP_COMMUNITY: "${SNMP_COMMUNITY}"
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      SIDECAR_DISPATCHER: 1
    restart: unless-stopped
  librenms-syslogng:
    container_name: LibreNMS-Syslogng
    image: librenms/librenms
    hostname: librenms-syslogng
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
    volumes:
      - /home/config/librenms:/data
    ports:
      - 514:514
    environment:
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
      DB_HOST: db
      DB_NAME: librenms
      DB_USER: librenms
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_TIMEOUT: 60
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      MEMORY_LIMIT: 256M
      UPLOAD_MAX_SIZE: 16M
      OPCACHE_MEM_SIZE: 128
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      LOG_IP_VAR: remote_addr
      LIBRENMS_SNMP_COMMUNITY: "${SNMP_COMMUNITY}"
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      SIDECAR_SYSLOGNG: 1
    restart: unless-stopped
  librenms-snmptrapd:
    container_name: LibreNMS-SNMPtrapd
    image: librenms/librenms
    hostname: librenms-snmptrapd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
    volumes:
      - /home/config/librenms:/data
    ports:
      - 162:162
    environment:
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
      DB_HOST: db
      DB_NAME: librenms
      DB_USER: librenms
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_TIMEOUT: 60
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      MEMORY_LIMIT: 256M
      UPLOAD_MAX_SIZE: 16M
      OPCACHE_MEM_SIZE: 128
      REAL_IP_FROM: 0.0.0.0/32
      REAL_IP_HEADER: X-Forwarded-For
      LOG_IP_VAR: remote_addr
      LIBRENMS_SNMP_COMMUNITY: "${SNMP_COMMUNITY}"
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      SIDECAR_SNMPTRAPD: 1
    restart: unless-stopped
