version: '3.8'
services:
  monitoror:
    container_name: Monitoror
    image: monitoror/monitoror
    ports:
      - 9012:8080
    volumes:
      - /mnt/gluster/containers/monitoror:/configs
    environment:
      MO_CONFIG: /configs/config.json
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-browser.entrypoints=https"
      - "traefik.http.routers.file-browser.tls=true"
      - "traefik.http.routers.file-browser.rule=Host(`monitoror.hyvecloud.dev`)"
      - "traefik.http.routers.file-browser.service=monitoror-monitoror@docker"
networks:
  proxy:
    external: true
