version: '3.8'
services:
  omada-controller:
    container_name: Omada-Controller
    image: mbentley/omada-controller:5.9
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    environment:
      MANAGE_HTTP_PORT: 15006
      MANAGE_HTTPS_PORT: 15007
      PORTAL_HTTP_PORT: 15008
      PORTAL_HTTPS_PORT: 15009
      PORT_APP_DISCOVERY: 27001
      PORT_ADOPT_V1: 29812
      PORT_UPGRADE_V1: 29813
      PORT_MANAGER_V1: 29811
      PORT_MANAGER_V2: 29814
      PORT_DISCOVERY: 29810
      SHOW_SERVER_LOGS: true
      TZ: Europe/London
    volumes:
      - /home/config/omada/data:/opt/tplink/EAPController/data
      - /home/config/omada/logs:/opt/tplink/EAPController/logs