version: "3.8"
services:
  unifi-controller:
    container_name: Unifi-Controller
    image: lscr.io/linuxserver/unifi-controller
    volumes:
      - /home/config/unifi-controller:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
