version: "3.8"
networks:
  drawionet:
services:
  drawio-image-export:
    container_name: DrawIO-Exporter
    image: jgraph/export-server
    volumes:
      - /home/config/drawio-export/fonts:/usr/share/fonts/drawio
    expose:
      - '8000'
    networks:
      - drawionet
    environment:
      DRAWIO_SERVER_URL: "${DRAWIO_BASE_URL}"
    restart: unless-stopped

  drawio:
    container_name: DrawIO
    image: jgraph/drawio
    depends_on:
      - drawio-image-export
    ports:
      - "14006:8443"
      - "14005:8080"
    networks:
      - drawionet
    environment:
      EXPORT_URL: http://192.168.0.243:8000/
      DRAWIO_BASE_URL: "${DRAWIO_BASE_URL}"
    restart: unless-stopped