version: '3.8'
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: Homepage
    ports:
      - 15003:3000
    volumes:
      - /home/config/homepage:/app/config
    restart: unless-stopped