version: '3'
services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    volumes:
      - /mnt/gluster/containers/traefik/:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped